### ISSUE TITLE
Problem loading first toot of a thread

### ISSUE THREAD

**Issue by kix2902** [vrutkovs/masto-thread-renderer#1]
I have discovered your website and doing some tests it appears it's unable to fetch the first toot of a thread (at least in the instance Ive my account), I tried with 2 threads and both fails exactly with the same problem:

Sample 1: https://thread.vrutkovs.eu/thread?url=https://paquita.masto.host/web/@kix2902/109321461673248249
Sample 2: https://thread.vrutkovs.eu/thread?url=https://paquita.masto.host/web/@fbpsy/109324101858715415

**Comment by vrutkovs** [comment]
Weird, I can't reproduce it. [Sample 1](https://thread.choomba.one/thread?url=https%3A%2F%2Fpaquita.masto.host%2Fweb%2F%40kix2902%2F109321461673248249) shows first toot as embedded toot and on markdown too

**Comment by kix2902** [comment]
It seems it was a bad time for the mastodon API or instance, this issue can be closed.
