### ISSUE TITLE
Include images in markdown export. 

### ISSUE THREAD

**Issue by arthurzenika** [vrutkovs/masto-thread-renderer#3]
Hey, great tool. Thanks for sharing it. 

Would it be possible to include markdown for the images attached to the toots ? 

Example : https://thread.choomba.one/markdown?url=https%3A%2F%2Fpouet.chapril.org%2F%40arthurzenika%2F112077075342540066 in the web view, we can see the images, but not in the markdown version

That could be an option if this is not useful to most ?

**Comment by vrutkovs** [comment]
The markdown version can probably have links to them - or you'd like to have image contents encoded there too?

**Comment by arthurzenika** [comment]
The two solutions would be nice. The first one fits better my first workaround to copy a thread content to a blog (as described in https://github.com/GetPublii/Publii/issues/1425) 

I don't see how the second would work, you would base64/mime encode the content ?

**Comment by vrutkovs** [comment]
Right, the images can be base64 encoded and you'd have one markdown with everything, perfectly portable.
That however sounds like an overkill, its not meant to be a backup tool after all.

Keeping image links seems to be the most fitting

**Comment by vrutkovs** [comment]
Fixed in b0b6981
