### ISSUE TITLE
Add link to source

### ISSUE THREAD

**Issue by niccokunzmann** [vrutkovs/masto-thread-renderer#6]
I just looked at https://mtr.wildeboer.net/ and I would like to see a link to this repo.

**Comment by jwildeboer** [comment]
It's right there, at the bottom of the page :)

<img width="573" alt="Screenshot 2024-06-23 at 17 33 26" src="https://github.com/vrutkovs/masto-thread-renderer/assets/873028/1e5dd154-6614-41ea-b02e-ad6ede3ffa2f">

The link called "Source" goes to here :)

**Comment by niccokunzmann** [comment]
Ohhh! I must be blind. Sure.. I expected it in a footer at the bottom...
