### ISSUE TITLE
Add examples and change place holder

### ISSUE THREAD

**Issue by niccokunzmann** [vrutkovs/masto-thread-renderer#8]
I would like the placeholder to show a valid URL that can be used.

```
placeholder="Search"
```

It is not a search. I entered a hashtag to search for it.

I.e. if I input an instance, it also does not work

- instance: https://mtr.wildeboer.net/thread?url=toot.wales
- username + instance: https://mtr.wildeboer.net/thread?url=toot.wales%2Fniccokunzmann
- handle: https://mtr.wildeboer.net/thread?url=%40niccokunzmann%40toot.wales
- hashtag: https://mtr.wildeboer.net/thread?url=%23OpenWebCalendar%40toot.wales

I would like them to work in a way that they guide the user.

Please provide examples.

**Comment by jwildeboer** [comment]
Makes sense. Should be "Post link to toot", maybe followed by an example.

**Comment by niccokunzmann** [comment]
I think, I would like it to have this content: https://social.wildeboer.net/@jwildeboer/112660999565383308
